import "./globals.css";
import ThemeProviderWrapper from "../provider/themeProvider";
import CssBaseline from "@mui/material/CssBaseline";
import ReduxProvider from "@/provider/ReduxProvider";
import DatePickerProvider from "@/provider/DatePickerProvider";
import SnackbarProvider from "@/provider/SnackbarProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProviderWrapper>
        <SnackbarProvider>
          <DatePickerProvider>
            <CssBaseline />
            <ReduxProvider>{children}</ReduxProvider>
          </DatePickerProvider>
        </SnackbarProvider>
        </ThemeProviderWrapper>
      </body>
    </html>
  );
}
