import "./globals.css";
import ThemeProviderWrapper from "../provider/themeProvider";
import CssBaseline from "@mui/material/CssBaseline";
import ReduxProvider from "@/provider/ReduxProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProviderWrapper>
          <CssBaseline />
          <ReduxProvider>{children}</ReduxProvider>
        </ThemeProviderWrapper>
      </body>
    </html>
  );
}
